#Citizenship Config

#   Debug ( max / full / Default:normal / none )
Debug: normal

#   MySQL Settings
mysql:
  host: localhost
  port: 3306
  database: LoginList
  username: root
  password: password

#Citizenship Rank
Rank:
  - NewFace,0
  - Civilian,24
  - Citizen,100
  - Nation,200
  - Uiverse,500
