#Citizenship Config

#   Debug ( max / full / Default:normal / stop )
Debug: normal

#   MySQL Settings
mysql:
  host: localhost
  port: 3306
  database: Citizenship
  username: root
  password: password

#   Citizenship Rank
#   WorldGuard に設定されているグループ名を正しく指定する事
#   グループ名、昇格に必要な時間（ｈ）または日数（ｄ）
Rank:
  - NewFace,24,H
  - Civilian,100,h
  - Citizen,200,D
  - Nation,500,d
  - Uiverse,0,E

#   降格判定　日数、ゼロならば降格無し
Demotion: 10

#   昇格時Broadcastアナウンスを行うか
PromotBroadcast: true

#   降格時Broadcastアナウンスを行うか
DemotBroadcast: false

#   牢獄の設定
#   権限剥奪時のグループ名(WorldGuardに設定しているもの)
PrisonGroup: Prisoner
#   剥奪解除に必要な時間（日数）
PenaltyTime: 1
#   牢獄エリアの座標
Prison:
  enable: true
  world: world
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
#   釈放時の転送座標
Release:
  enable: true
  world: world
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

#   警戒コマンド一覧
Aleart:
    - OP
    - OPME
    - LOGIN
    - GAMEMODE
