#Citizenship Config

#   Debug ( max / full / Default:normal / none )
Debug: full

#   MySQL Settings
mysql:
  host: localhost
  port: 3306
  database: Citizenship
  username: root
  password: password

#   Citizenship Rank
#   WorldGuard に設定されているグループ名を正しく指定する事
#   グループ名、昇格に必要な時間（ｈ）
Rank:
  - NewFace,24
  - Civilian,100
  - Citizen,200
  - Nation,500
  - Uiverse,0

#   降格判定　日数、ゼロならば降格無し
Demotion: 10

#   昇格時Broadcastアナウンスを行うか
PlayerBroadcast: false

#   牢獄の設定
#   権限剥奪時のグループ名(WorldGuardに設定しているもの)
PrisonGroup: Prisoner
#   剥奪解除に必要な時間（日数）
PenaltyTime: 1
#   剥奪時、牢獄エリアにジャンプさせるか？
Imprisonment: false
#   牢獄エリアの座標
Prison:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
#   釈放時の転送座標
Release:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
