name: Citizenship
version: '1.2.1'
main: io.github.kumaisu.citizenship.Citizenship
api-version: '1.21'
description: Citizen Ship Auto Control plugin
author: NineTailedFox
database: true
softdepend: [Vault]
commands:
    yellow:
        description: Yellow Card Command
        permission: citizenship.yellow
        default: op
        permission-message: You do not have permission.
    jail:
        description: Jail Command
        permission: citizenship.jail
        default: op
        permission-message: You do not have permission.
    ranks:
        description: Citizenship Control Admin Commands
    fly:
        description: Flight Mode command
        permission: citizenship.fly
        permission-message: You do not have permission.
        default: op
permissions:
    citizenship.admin:
        description: Admin Command permissions
        permission-message: You do not have permission.
        default: op
    citizenship.console:
        description: Console Command permissions
        permission-message: You do not have permission.
        default: op
    citizenship.initialize:
        description: Player Force Initialize Command
        permission-message: You do not have permission.
        default: false
    citizenship.AlertPass:
        description: Ignore alert command check
        default: false
