main: com.mycompany.citizenship.Citizenship
name: Citizenship
version: 0.2
description: Citizenship Control Manager plugins
author: Kumaisu
database: true
commands:
    jail:
        description: Jail Command
        permission: Citizenship.jail
        default: op
        permission-message: You do not have permission.
        usage: /<command> <player>
    ranks:
        description: Citizenship Control Admin Commands
        permission: Citizenship.admin
        default: op
        permission-message: You do not have permission.
        usage: |
            /<command> promotion <player>
            /<command> demotion <player>
            /<command> time <player>
            /<command> Reload
            /<command> Status
            /<command> Console [full/normal/none]
permissions:
    citizenship.admin:
        description: Command Permission
        default: op
