main: com.mycompany.citizenship.Citizenship
name: Citizenship
version: 0.8.1
author: Kumaisu
database: true
commands:
    jail:
        description: Jail Command
        permission: citizenship.jail
        default: op
        permission-message: You do not have permission.
    ranks:
        description: Citizenship Control Admin Commands
permissions:
    citizenship.admin:
        description: Admin Command permissions
        permission-message: You do not have permission.
        default: op
    citizenship.console:
        description: Console Command permissions
        permission-message: You do not have permission.
        default: op
    citizenship.initialize:
        description: Player Force Initialize Command
        permission-message: You do not have permission.
        default: false
        
