main: com.mycompany.citizenship.Citizenship
name: Citizenship
version: 1.0.3
description: Citizen Ship Auto Control plugin
author: Kumaisu
database: true
api-version: 1.14
commands:
    yellow:
        description: Yellow Card Command
        permission: citizenship.yellow
        default: op
        permission-message: You do not have permission.
    jail:
        description: Jail Command
        permission: citizenship.jail
        default: op
        permission-message: You do not have permission.
    ranks:
        description: Citizenship Control Admin Commands
permissions:
    citizenship.admin:
        description: Admin Command permissions
        permission-message: You do not have permission.
        default: op
    citizenship.console:
        description: Console Command permissions
        permission-message: You do not have permission.
        default: op
    citizenship.initialize:
        description: Player Force Initialize Command
        permission-message: You do not have permission.
        default: false
