main: com.mycompany.citizenship.Citizenship
name: Citizenship
version: 0.3
description: Citizenship Control Manager plugins
author: Kumaisu
database: true
commands:
    jail:
        description: Jail Command
        permission: Citizenship.jail
        default: op
        permission-message: You do not have permission.
        usage: /<command> <player>
    ranks:
        description: Citizenship Control Admin Commands
        usage: /<command> <param>
permissions:
    citizenship.admin:
        description: Broadcast announce
        permission-message: You do not have permission.
        default: op
    citizenship.initialize:
        description: Broadcast announce
        permission-message: You do not have permission.
        default: false
        